- name: Show the URL of the tagged release
  debug: msg="Accessing the tagged release at {{ github_api }}/{{ github_owner }}/{{ github_repo }}/releases/tags/{{ github_tag }}"
  when: github_tag != ""

- name: Get the tagged release
  uri:
    url: "{{ github_api }}/{{ github_owner }}/{{ github_repo }}/releases/tags/{{ github_tag }}"
    return_content: yes
  register: releases
  when: github_tag != ""

- debug: msg="Version {{ github_tag }}"
- debug: msg="Content {{ releases }}"

- name: Show the URL of the release
  debug: msg="Accessing the lastest release at {{ github_api }}/{{ github_owner }}/{{ github_repo }}/releases/latest"
  when: github_tag == ""

- name: Get the latest release
  uri:
    url: "{{ github_api }}/{{ github_owner }}/{{ github_repo }}/releases/latest"
    return_content: yes
  register: releases
  when: github_tag == ""

- debug: msg="Version {{ github_tag }}"
- debug: msg="{{ releases.json }}"