- name: Get the Mac asset 
  include: mac_asset.yml
  with_items: "{{ assets.json }}"
  when: assets is defined and ansible_os_family == 'Darwin'

- name: Get the Linux asset
  include: linux_asset.yml
  with_items: "{{ assets.json }}"
  when: "assets is defined and ansible_os_family in ['RedHat', 'Debian']"

- name: Should have an asset_name
  assert:
    that: asset_name is defined

- name: Create a temp dir
  command: mktemp -d -t ansible.XXXXXXXXXX
  register: temp_output

- name: Show temp dir
  debug: msg="Temp dir - {{ temp_output.stdout }}"

- name: Show the asset name
  debug: msg="Asset name = {{ asset_name }}"

- name: Download the asset
  get_url:
    url: "{{ asset_url }}"
    dest: "{{ temp_output.stdout }}/{{ asset_name }}"

- name: Check if the 'kind' client exists within the tmp folder
  stat:
    path: "{{ temp_output.stdout }}/{{ asset_name }}"
  register: kind

- name: Copy 'kind' to the target directory if it exists within tmp folder
  copy:
    src: "{{ temp_output.stdout }}/{{ asset_name }}"
    dest: "{{ kind_client_dest }}/kind"
    mode: 0775
    remote_src: true
  when: kind.stat.exists

- name: Remove the temp directory
  file:
    path: "{{ temp_output.stdout }}"
    state: absent
