- name: Set the value of the github_tag if a kind version is specified
  set_fact:
    github_tag: "{{ kind_version }}"
  when: kind_version != ""

- name: Set force yes or no when kind must be re-installed
  set_fact:
    force: yes
  when: kind_force_client_install | bool == true

- name: Check if 'kind' binary exists
  stat:
    path: "{{ target_path}}/{{ kind_executable_name }}"
  register: kind_binary_present

- name: Show the URL and get the tagged release
  block:
    - debug: msg="Accessing the tagged release at {{ github_api }}/{{ github_owner }}/{{ github_repo }}/releases/tags/{{ github_tag }}"
    - uri:
        url: "{{ github_api }}/{{ github_owner }}/{{ github_repo }}/releases/tags/{{ github_tag }}"
        return_content: yes
      register: assets
  when: github_tag != ''

- debug: msg="github var {{ github_tag }}, json content {{ assets }}"

- name: Show the URL of the latest release and get it
  block:
    - debug: msg="Accessing the latest release at {{ github_api }}/{{ github_owner }}/{{ github_repo }}/releases/latest"
    - uri:
        url: "{{ github_api }}/{{ github_owner }}/{{ github_repo }}/releases/latest"
        return_content: yes
      register: assets
  when: github_tag == ""

- debug: msg="github var = {{ github_tag }}, json content = {{ assets }}"

- name: Download 'kind' binary from github & install it if missing from /usr/local/bin directory
  get_url:
    url: https://api.github.com/repos/{{ github_owner }}/{{ github_repo }}/releases/assets/{{ id }}
    headers:
      Accept: application/octet-stream
    dest: "{{ target_path }}/{{ kind_executable_name }}"
    mode: "{{ asset_mode }}"
    force: "{{ force }}"
  when: kind_force_client_install | bool == true or not kind_binary_present.stat.exists
  vars:
    release_data: "{{ assets.json|to_json }}"
    arch: "{{ ansible_system|lower }}-{{ arch_map[ansible_userspace_architecture] }}"
    id: "{{ release_data|from_json|json_query('assets[?ends_with(@.name, `' ~ arch ~ '`)] | [0].id') }}"