---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: docker.io/pycontribs/centos:7
    pre_build_image: true
    privileged: true
provisioner:
  name: ansible
  playbooks:
    cleanup: ../resources/cleanup.yml
    converge: ../resources/converge.yml
    # prepare: ../resources/prepare.yml
    verify: ../resources/verify.yml
  env:
    ANSIBLE_ROLES_PATH: ../../roles
lint: |
  set -e
  yamllint .
  ansible-lint
verifier:
  name: ansible
scenario:
  test_sequence:
    - dependency
    # - lint
    # - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    #- idempotence
    - side_effect
    - verify
    - cleanup
    - destroy